version: "3"
services:

  count:
    build: .
    restart: always
    container_name: moe_count
    ports:
      - 8085:8080
    volumes:
      - ./db/users.db:/app/users.db
    networks:
      infra_network:
        aliases:
          - infra_network
    # environment:
      # DATABASE: postgres
      # DB_USER: postgres
      # DB_PASS: SomeSecurePassword
      # DB_HOST: db
      # DB_PORT: 5432
    # command: ["-dbname=postgres", "-dbuser=postgres", "-dbpassword=SomeSecurePassword","-dbhost=db", "-dbport=5432"]


  db:
    image: postgres:10
    restart: always
    container_name: infra_postgres
    environment:
      POSTGRES_PASSWORD: "SomeSecurePassword"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "0.5"
        reservations:
          memory: "1G"
          cpus: "0.5"
    networks:
      infra_network:
        aliases:
          - infra_postgres

networks:
  infra_network: