version: "3"
services:

  db:
    image: postgres:10
    restart: always
    container_name: infra_postgres
    environment:
      POSTGRES_PASSWORD: "SomeSecurePassword"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "0.5"
        reservations:
          memory: "1G"
          cpus: "0.5"
    networks:
      infra_network:
        aliases:
          - infra_postgres

networks:
  infra_network: